name: Staging deploy
on:
  workflow_dispatch:
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME}}
          key: ${{secrets.STAGING_KEY}}
          port: ${{secrets.STAGING_PORT}}
          script: |
            cd apps/blog/strapi-blog-next
            echo | ls
            echo "***** ***** **** ***** ***** **** ***** ***** ****"
            echo | git config --list
            echo | ssh -T git@github.com
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            /root/.nvm/versions/node/v16.20.0/bin/npx next build
            /root/.nvm/versions/node/v16.20.0/bin/pm2 restart blog-front
