name: Staging deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME}}
          key: ${{secrets.STAGING_KEY}}
          port: ${{secrets.STAGING_PORT}}
          script: |
            cd apps/blog/strapi-blog-next
            git pull
            npm run build
            pm2 restart blog-front
